#!/bin/sh

# Abbreviations for common commands
alias ka="killall" \
		ra="ranager" \
		v="$EDITOR" \
		p="pacman"

# Common configs
alias vrc="vim $HOME/.config/nvim/init.vim"

# Commands with color
alias ls="ls -hN --color=auto --group-directories-first" \
		grep="grep --color=auto"

alias dot="/usr/bin/git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME" \
