#!/bin/sh

# Abbreviations for common commands
alias \
		ka="killall" \
		ra="ranager" \
		e="$EDITOR" \
		p="pacman"

# Common configs
alias \
		vrc="nvim $HOME/.config/nvim/init.vim"

# Commands with color
alias \ 
		ls="ls -hN --color=auto --group-directories-first" \
		grep="grep --color=auto" \ 
		diff="diff --color=auto"

# Verbosity and useful settings
alias \ 
		cp="cp -iv" \ 
		mv="mv -iv" 

# Alias for dotfiles
alias \
		dot="/usr/bin/git --git-dir=$HOME/.config/dotfiles --work-tree=$HOME"
