#!/bin/zsh

# Default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave"

# XDG 
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export XDG_STATE_HOME=$HOME/.local/state

# $HOME clean up 
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export LESSHISTFILE="-"
export RANGER_LOAD_DEFAULT_RC="False"
