#!/bin/sh

[ -f $HOME/.config/shell/profile ] && . $HOME/.config/shell/profile

. ~/.local/bin/setbg
setbg & 
xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="mpd dunst pipewire wireplumber"

for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
